//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTIModManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSTIModManager.Resources.Strings.zh-CN", typeof(Strings_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入Discord.
        /// </summary>
        internal static string buttonDiscordLink_Text {
            get {
                return ResourceManager.GetString("buttonDiscordLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装/更新.
        /// </summary>
        internal static string buttonInstall_Text {
            get {
                return ResourceManager.GetString("buttonInstall.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除Mod.
        /// </summary>
        internal static string buttonModInfo_Text {
            get {
                return ResourceManager.GetString("buttonModInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奇幻森林log目录.
        /// </summary>
        internal static string buttonOpenLogFolderCSFF_Text {
            get {
                return ResourceManager.GetString("buttonOpenLogFolderCSFF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热带岛屿log目录.
        /// </summary>
        internal static string buttonOpenLogFolderCSTI_Text {
            get {
                return ResourceManager.GetString("buttonOpenLogFolderCSTI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看Wiki.
        /// </summary>
        internal static string buttonOpenWiki_Text {
            get {
                return ResourceManager.GetString("buttonOpenWiki.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用/禁用.
        /// </summary>
        internal static string buttonToggleMods_Text {
            get {
                return ResourceManager.GetString("buttonToggleMods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到BepInEx!\n\n是否安装？.
        /// </summary>
        internal static string Cant_find_bepinex_text {
            get {
                return ResourceManager.GetString("Cant find bepinex text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到BepInEx.
        /// </summary>
        internal static string Cant_find_bepinex_title {
            get {
                return ResourceManager.GetString("Cant find bepinex title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.log 文件未找到.
        /// </summary>
        internal static string Cant_find_log {
            get {
                return ResourceManager.GetString("Cant find log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取文件大小信息.
        /// </summary>
        internal static string Cant_get_file_size {
            get {
                return ResourceManager.GetString("Cant get file size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.log 文件为空.
        /// </summary>
        internal static string Cant_load_log {
            get {
                return ResourceManager.GetString("Cant load log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法从 Player.log 中解析游戏路径.
        /// </summary>
        internal static string Cant_load_path_from_log {
            get {
                return ResourceManager.GetString("Cant load path from log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到有版本更新，请使用新版本.
        /// </summary>
        internal static string Check_update_success_text {
            get {
                return ResourceManager.GetString("Check update success text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有新的更新可用!.
        /// </summary>
        internal static string Check_update_success_title {
            get {
                return ResourceManager.GetString("Check update success title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新中....
        /// </summary>
        internal static string Checking_update {
            get {
                return ResourceManager.GetString("Checking update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string columnHeaderAuthorCSFF_Text {
            get {
                return ResourceManager.GetString("columnHeaderAuthorCSFF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string columnHeaderAuthorCSTI_Text {
            get {
                return ResourceManager.GetString("columnHeaderAuthorCSTI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地版本.
        /// </summary>
        internal static string columnHeaderLocalVersionCSFF_Text {
            get {
                return ResourceManager.GetString("columnHeaderLocalVersionCSFF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地版本.
        /// </summary>
        internal static string columnHeaderLocalVersionCSTI_Text {
            get {
                return ResourceManager.GetString("columnHeaderLocalVersionCSTI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string columnHeaderNameCSFF_Text {
            get {
                return ResourceManager.GetString("columnHeaderNameCSFF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string columnHeaderNameCSTI_Text {
            get {
                return ResourceManager.GetString("columnHeaderNameCSTI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 云端版本.
        /// </summary>
        internal static string columnHeaderVersionCSFF_Text {
            get {
                return ResourceManager.GetString("columnHeaderVersionCSFF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 云端版本.
        /// </summary>
        internal static string columnHeaderVersionCSTI_Text {
            get {
                return ResourceManager.GetString("columnHeaderVersionCSTI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除.
        /// </summary>
        internal static string Confirm_deletion {
            get {
                return ResourceManager.GetString("Confirm deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接服务器....
        /// </summary>
        internal static string Connect_to_server {
            get {
                return ResourceManager.GetString("Connect to server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奇幻森林.
        /// </summary>
        internal static string CSFF_Text {
            get {
                return ResourceManager.GetString("CSFF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热带岛屿.
        /// </summary>
        internal static string CSTI_Text {
            get {
                return ResourceManager.GetString("CSTI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你正在尝试删除所选Mods文件. 该操作不可撤销!\n\n你确定要继续吗?.
        /// </summary>
        internal static string Delete_Mod {
            get {
                return ResourceManager.GetString("Delete Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除完成!.
        /// </summary>
        internal static string Delete_Mod_success {
            get {
                return ResourceManager.GetString("Delete Mod success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除Mod！.
        /// </summary>
        internal static string Deleting_Mod {
            get {
                return ResourceManager.GetString("Deleting Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用Mod！.
        /// </summary>
        internal static string Disable_Mod {
            get {
                return ResourceManager.GetString("Disable Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (已禁用).
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载失败:.
        /// </summary>
        internal static string Download_failed {
            get {
                return ResourceManager.GetString("Download failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成！.
        /// </summary>
        internal static string Download_success {
            get {
                return ResourceManager.GetString("Download success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已下载:.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载中: .
        /// </summary>
        internal static string Downloading_information {
            get {
                return ResourceManager.GetString("Downloading information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用Mod！.
        /// </summary>
        internal static string Enable_Mod {
            get {
                return ResourceManager.GetString("Enable Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误！.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件大小: .
        /// </summary>
        internal static string File_size {
            get {
                return ResourceManager.GetString("File size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏路径不存在.
        /// </summary>
        internal static string Game_path_does_not_exist {
            get {
                return ResourceManager.GetString("Game path does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未指定游戏路径.
        /// </summary>
        internal static string Game_path_not_specified {
            get {
                return ResourceManager.GetString("Game path not specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动检测奇幻森林游戏路径失败，请稍后手动添加。.
        /// </summary>
        internal static string Get_CSFF_path_error {
            get {
                return ResourceManager.GetString("Get CSFF path error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动检测热带岛屿游戏路径失败，请稍后手动添加。.
        /// </summary>
        internal static string Get_CSTI_path_error {
            get {
                return ResourceManager.GetString("Get CSTI path error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取Mod信息....
        /// </summary>
        internal static string Get_MOD_Information {
            get {
                return ResourceManager.GetString("Get MOD Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取更新信息失败，请稍后重试.
        /// </summary>
        internal static string Get_update_error {
            get {
                return ResourceManager.GetString("Get update error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取更新信息失败，请检查您的网络连接.
        /// </summary>
        internal static string Get_update_net_error {
            get {
                return ResourceManager.GetString("Get update net error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gitee.com/Cold_winds/cstimod-manager/releases/latest.
        /// </summary>
        internal static string Gitee {
            get {
                return ResourceManager.GetString("Gitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Coldwinds5167/CSTIModManager/releases/latest.
        /// </summary>
        internal static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装过程中会启动一次游戏，\n\n请等待游戏加载完成后再关闭!\n\n是否继续？.
        /// </summary>
        internal static string Install_Bepinex_hint {
            get {
                return ResourceManager.GetString("Install Bepinex hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装完成！.
        /// </summary>
        internal static string Installation_complete {
            get {
                return ResourceManager.GetString("Installation complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (已安装).
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在安装....
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在安装...BepInEx.
        /// </summary>
        internal static string Installing_bepinex {
            get {
                return ResourceManager.GetString("Installing bepinex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热带岛屿游戏路径:.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奇幻森林游戏路径:.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重要路径.
        /// </summary>
        internal static string labelOpen_Text {
            get {
                return ResourceManager.GetString("labelOpen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态: 无.
        /// </summary>
        internal static string labelStatus_Text {
            get {
                return ResourceManager.GetString("labelStatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod信息获取成功！.
        /// </summary>
        internal static string Mod_information_retrieved_successfully {
            get {
                return ResourceManager.GetString("Mod information retrieved successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这不是 Card Survival - Fantasy Forest.exe! 请重试!.
        /// </summary>
        internal static string Not_CSFF {
            get {
                return ResourceManager.GetString("Not CSFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这不是 Card Survival - Tropical Island.exe! 请重试!.
        /// </summary>
        internal static string Not_CSTI {
            get {
                return ResourceManager.GetString("Not CSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始安装队列....
        /// </summary>
        internal static string Start_installation_queue {
            get {
                return ResourceManager.GetString("Start installation queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户取消操作.
        /// </summary>
        internal static string User_canceled_the_operation {
            get {
                return ResourceManager.GetString("User canceled the operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杂项.
        /// </summary>
        internal static string Utilities_Text {
            get {
                return ResourceManager.GetString("Utilities.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看信息.
        /// </summary>
        internal static string viewInfoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("viewInfoToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
